### ISSUE TITLE
Install Databases

### ISSUE THREAD

**Issue by Ze3osint** [GONZOsint/geowifi#1]
Hi, I'm OSINT beginner and student. 

How Do i install a databases new in the case OpenWiFi ? 

Thanks!

**Comment by GONZOsint** [comment]
What do you mean by installing a new database? 

All the necessary steps to install the tool are in the [README](https://github.com/GONZOsint/geowifi/blob/main/README.md).

**Comment by Ze3osint** [comment]
I try run the -s (ssid), but the error occurs:

![image](https://user-images.githubusercontent.com/98282329/157509263-9e8407e0-7e57-488a-af92-5a6cdd0011c4.png)

**Comment by alabrian-tr** [comment]
@Ze3osint did you obtain an API key from Wigle and add it in `utils/API.yaml` ?

**Comment by daydr3am3r** [comment]
@Ze3osint did you obtain an API key from Wigle and add it in `utils/API.yaml` ?

**Comment by jpmortaza** [comment]
> Eu tento executar o -s (ssid), mas ocorre o erro:
> 
> ![imagem](https://user-images.githubusercontent.com/98282329/157509263-9e8407e0-7e57-488a-af92-5a6cdd0011c4.png)


You need - Coded to use: - available at https://wigle.net/account. Do not insert any utils/API.yaml file
